version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongodb
    versions:
    - 3.6.4
    - 3.6.5
  - dependency-name: express-validator
    versions:
    - 6.10.0
    - 6.9.2
  - dependency-name: express-handlebars
    versions:
    - 5.2.1
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
  - dependency-name: monk
    versions:
    - 7.3.3
