version: "2"
services:
    app:
        container_name: waptr
        restart: always
        build: .
        command: /bin/sh -c "npm install && npm install -g nodemon && nodemon --watch server --watch views --watch lib server.js"
        volumes:
            - .:/app
        ports:
            - "5000:5000"
        links:
            - waptrdb

    waptrdb:
        container_name: waptrdb
        restart: always
        volumes:
            - .:/app
        image: mongo
        ports:
            - "27017:27017"
