version: "2"
services:
    waptrun:
        container_name: waptrun
        build: .
        command: /bin/sh -c "npm install && node_modules/.bin/nodemon --watch server --watch package.json server/server.js"
        volumes:
            - .:/app
        ports:
            - "5000:5000"
        links:
            - waptrdb

    waptrdb:
        container_name: waptrdb
        volumes:
            - .:/app
        image: mongo
        ports:
            - "27017:27017"

    hack-tools:
        container_name: hack-tools
        build: ./hack-tools
        #volumes:
        #    - ./hack-tools:/app
        ports:
            - "5001:5001"
